language: node_js
node_js:
  - "7"

after_success:
  - npm run test
  - npm run coverage
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info

addons:
  code_climate:
    repo_token: 794bc635d40b80b41aa60ef22b601ff071a5a72cb35dd5317e911327f47b41d1

after_failure:
  - npm run coverage
  