language: node_js
node_js:
  - "7"

after_success:
  - npm run test
  - npm run coverage

addons:
  code_climate:
    repo_token: 2c6b5b8dfab364bb9027baa2121d55965c226677cf5c650daa9604bb419fb184

after_failure:
  - npm run coverage
  